name: scraper

services:
  backend:
    container_name: scraper-backend
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: python3 manage.py runserver 0.0.0.0:${PORT}
